### ISSUE TITLE
ImageNet-30 models

### ISSUE THREAD

**Issue by ajevnisek** [kobybibas/pnml_ood#3]
Thank you very much for a very reproducible-oriented repository!

Can you please publish your ImageNet-30 models (ResNet-18 & ResNet-101) so we can run pNML and evaluate OOD detection performance rates on them?
I think the easiest way would be to add it to the `bash_scripts/download_models.sh` file.

Thanks!

**Comment by ajevnisek** [comment]
Used pretrained imagenet18 and imagenet101

**Comment by kobybibas** [comment]
The pre-trained model for ImangeNet-30 is the default Pytorch pre-trained model https://pytorch.org/vision/stable/models.html#id10
